Add extension for relative time and fix a bug
krawieck/lemmur pull request #151
Opened 2021-02-12 16:55 UTC by krawieck

fixes #150 

the bug was that time from server is in UTC format,
and our time is in local format, so it needed
to be shifted back to UTC.

oddly enough .toUtc() method didn't work

2021-02-12 18:52 UTC, shilangyu approved these changes

2021-02-12 18:52 UTC, shilangyu commented on lib/util/extensions/datetime.dart
> +  /// returns [this] time as a relative, human-readable string. In short format
`[this]` doesn't link to anything

2021-02-12 18:52 UTC, shilangyu commented on lib/util/extensions/datetime.dart
> +  String get fancy => timeago.format(this,
I really don't understand why the word 'fancy' was chosen

2021-02-12 19:12 UTC, shilangyu commented on lib/util/extensions/datetime.dart
> +  /// returns [this] time as a relative, human-readable string. In short format
Nevermind, I'm stupid

2021-02-13 01:24 UTC, dessalines commented
I don't know about darts fromUtc libraries, but this should work : https://stackoverflow.com/a/60188960

2021-02-13 16:12 UTC, shilangyu requested changes

2021-02-13 16:12 UTC, shilangyu commented on pubspec.yaml
> +
:thinking:

2021-02-13 16:17 UTC, merged