Lemmy 0.11.0
krawieck/lemmur pull request #226
Opened 2021-04-28 13:34 UTC by shilangyu

2021-04-28 13:41 UTC, shilangyu commented
I don't like the 'presentName' name, I'll be happy to accept alternatives

2021-04-29 08:59 UTC, krawieck requested changes
it's all good, just one minor change

2021-04-29 08:59 UTC, krawieck commented on lib/widgets/user_profile.dart
> +                userView.person.presentName,
change `presentName -> preferredName`

2021-04-29 09:39 UTC, krawieck approved these changes

2021-04-29 09:43 UTC, merged