Feature/logging
krawieck/lemmur pull request #251
Opened 2021-09-07 20:08 UTC by shilangyu

- add logging, forbid use of `print`
- TODO: add way to copy recent logs
- TODO: add to issue template place for recent logs
- split lemmur into two flavors: dev and prod
- refactor CI to run lint first before running anything else

2021-09-22 17:30 UTC, shilangyu commented on lib/pages/log_console/log_console.dart
> +      appBar: AppBar(),
Add close button

2021-09-22 17:53 UTC, krawieck requested changes

2021-09-22 17:53 UTC, krawieck commented on lib/pages/log_console/log_console.dart
> +class LogConsoleRoute extends MaterialPageRoute {
CupertinoRoute

2021-09-23 16:55 UTC, shilangyu commented on lib/pages/log_console/log_console.dart
> +      appBar: AppBar(),
Nvm, it is added by default when `fullscreenDialog == true`

2021-09-23 17:05 UTC, krawieck approved these changes

2021-09-23 17:25 UTC, merged