Fix overflows
krawieck/lemmur pull request #274
Opened 2021-10-31 11:56 UTC by shilangyu

2021-11-02 23:30 UTC, krawieck requested changes

2021-11-02 23:30 UTC, krawieck commented on lib/widgets/post/post_info_section.dart
> +              ),
padding is displayed when it shouldn't. when hide avatars is set to true.
![telegram-cloud-photo-size-4-6048701244840720195-x](https://user-images.githubusercontent.com/10037914/139964508-1795b245-fe44-43b9-b394-813c58ee4a32.jpg)

2021-11-02 23:30 UTC, krawieck commented on lib/widgets/user_profile.dart
>            )
since you're editing user profile could you also change it so that the background image fits better into the space that it has?

2021-11-03 05:21 UTC, closed without merging

2021-11-03 07:35 UTC, shilangyu commented
Apparently github is unable to redirect base branches once they are merged. I am unable to reopen this PR. I'll create a new one.