Migrate modlog to mobx
krawieck/lemmur pull request #303
Opened 2021-11-25 22:52 UTC by shilangyu

2021-11-29 13:07 UTC, krawieck requested changes

2021-11-29 13:07 UTC, krawieck commented on lib/pages/modlog/modlog_page_store.dart
> +    fetchPage();
could be called through reaction

2021-11-29 22:56 UTC, shilangyu reviewed
Add tests

2021-12-04 15:54 UTC, krawieck approved these changes

2021-12-04 17:03 UTC, merged