Instance page
krawieck/lemmur pull request #33
Opened 2020-09-08 21:02 UTC by krawieck

only info tab for now

2020-09-08 21:14 UTC, krawieck commented
Screenshots:
![Simulator Screen Shot - iPhone 11 - 2020-09-08 at 23 11 10](https://user-images.githubusercontent.com/10037914/92528369-f28a8780-f228-11ea-8a37-0b7036289e8e.png)
![Simulator Screen Shot - iPhone 11 - 2020-09-08 at 23 11 21](https://user-images.githubusercontent.com/10037914/92528376-f4ece180-f228-11ea-9288-2fd78f4f2000.png)
![Simulator Screen Shot - iPhone 11 - 2020-09-08 at 23 11 30](https://user-images.githubusercontent.com/10037914/92528378-f61e0e80-f228-11ea-8872-6bc15e32e926.png)
![Simulator Screen Shot - iPhone 11 - 2020-09-08 at 23 11 38](https://user-images.githubusercontent.com/10037914/92528394-f9b19580-f228-11ea-963b-25bfa9651d25.png)
![Simulator Screen Shot - iPhone 11 - 2020-09-08 at 23 11 33](https://user-images.githubusercontent.com/10037914/92528397-fb7b5900-f228-11ea-8e04-5677273ec77d.png)

2020-09-09 08:58 UTC, shilangyu requested changes

2020-09-09 08:58 UTC, shilangyu commented on lib/pages/communities_list.dart
> +            title: Text(communities[i].name ?? '@${communities[i].name}'),
The name is never `null`

2020-09-09 08:58 UTC, shilangyu commented on lib/pages/communities_list.dart
> +  void goToUser(BuildContext context, int id) {
should be go to community

2020-09-09 08:58 UTC, shilangyu commented on lib/pages/instance.dart
> +                )),
Maybe we shouldn't show recently banned and just leave a button "show banned users"

2020-09-09 08:58 UTC, shilangyu commented on lib/pages/instance.dart
> +                '${site.site.name}',
No need to interpolate a string into a string

2020-09-09 08:58 UTC, shilangyu commented on lib/pages/instance.dart
> +          // padding: EdgeInsets.only(top: 0),
remove if not used

2020-09-09 08:58 UTC, shilangyu commented on lib/pages/instance.dart
> +                      (e.preferredUsername == null || e.preferredUsername == '')
use `.isEmpty`

2020-09-09 08:58 UTC, shilangyu commented on lib/pages/instance.dart
> +                  // subtitle: Text(),
remove unused

2020-09-09 09:38 UTC, shilangyu approved these changes

2020-09-09 09:38 UTC, merged